# Цветная Триодь

Цветная Триодь включает в себя богослужебные последования пасхального цикла, то есть круг подвижных праздников от самой Пасхи до Недели Всех святых, даты которых меняются в зависимости от дня празднования Пасхи.

Высокая значимость Цветной Триоди как компонента годового круга церковных служений способствовала выбору этого текста в качестве материала для нашей работы.

Греческий текст Цветной Триоди выгружен с [сайта Греческой православной архиепископии Америки](https://glt.goarch.org/#04).

Церковнославянский текст Цветной Триоди выгружен с [сайта проекта «Азбука веры»](https://azbyka.ru/otechnik/Pravoslavnoe_Bogosluzhenie/triod-tsvetnaja/).

## **Специфика текста Цветной триоди**

### Темпоральная структура

Цветная триодь имеет строгую внутреннюю временную структуру, которая включает в себя следующие уровни:

-   Неделя

-   День недели

-   Служба

---\> На уровне темпоральной организации от элайнера ожидается строгое выравнивание элементов в билингвальном корпусе: неделя к неделе, день ко дню ИЛИ требуется разметка текста, которая бы позволила работать на более мелких уровнях, а не выравнивать текст целиком

### Функциональная структура

Внутри текста Цветной Триоди можно выделить 2 уровня:

-   служебные комментариями по организации и проведению службы

-   тексты молитв и песнопений

---\> Бинарная функциональная структура является одной из причин расхождения длины богослужебных текстов для разных языков. Так, в греческом тексте Цветной Триоди служебные комментарии представлены в значительно сокращенном виде по сравнению со схожими элементами церковнославянского текста. 

### Порядок следования фрагментов

Тексты песнопений на различных языках могут иметь отличный друг от друга порядок следований, что создает перекрестную структуру внутри билингвального корпуса и значительно усложняет задачу параллельного выравнивания.

---\> Разрозненный порядок следования молитв внутри элементов службы или дня затрудняет работу классических элайнеров (см.пункт "Готовые решения"). Необходимо устанавливать широкое окно для оценки близости различных компонентов

### Тексты молитв

В текстах Цветной Триоди на обоих языках молитвы могут быть представлены как в сокращенном формате, так и целиком.

После текста молитвы может следовать как краткое служебное указание о повторении молитвы. В иных случаях, текст молитвы может дублироваться полностью в последующих абзацах, повторяясь необходимое количество раз для исполнения во время службы.

---\> Для решения задачи по выравниванию корпуса требуется нормализация сводимых элементов.
