# Пример: Пасхальный канон Иоанна Дамаскина

Посмотрим еще раз на фрагмент Пасхального канона Иоанна Дамаскина. Ниже приведены части текстов в том порядке, в каком они представлены в источниках.

::: {.callout-tip collapse="true" icon="false" appearance="simple" title="Фрагмент церковнославянского текста"}
Канон Пасхальный, глас 1:

Пасхальный канон поется полностью хором: и ирмосы, и припевы, и тропари, и катавасии.

На каждой песни канона совершается каждение.

При соборном служении каждение совершают все иереи поочередно (а при большом числе иереев -- попарно).

Песнь 1:

Ирмос: Воскресе́ния день, просвети́мся, лю́дие. Па́сха, Госпо́дня Па́сха: от сме́рти бо к жи́зни, и от земли́ к небеси́, Христо́с Бог нас преведе́, побе́дную пою́щия. (Четырежды)

Припев: Христо́с воскре́се из ме́ртвых.

Очи́стим чу́вствия, и у́зрим непристу́пным све́том Воскресе́ния, Христа́ блиста́ющася, и ра́дуйтеся, реку́ща, я́сно да услы́шим, побе́дную пою́ще. (6 раз)

Небеса́ у́бо досто́йно да веселя́тся, земля́ же да ра́дуется, да пра́зднует же мир, ви́димый же весь и неви́димый: Христо́с бо воста́, весе́лие ве́чное. (6 раз)
:::

::: {.callout-tip collapse="true" icon="false" appearance="simple" title="Фрагмент греческого текста"}
Ὁ Κανών, ποίημα Ἰωάννου τοῦ Δαμασκηνοῦ.

ᾨδὴ α' Ἦχος α' εἱρμὸς

«Ἀναστάσεως ἡμέρα λαμπρυνθῶμεν Λαοί, Πάσχα Κυρίου, Πάσχα· ἐκ γὰρ θανάτου πρὸς ζωήν, καὶ ἐκ γῆς πρὸς οὐρανόν, Χριστὸς ὁ Θεός, ἡμᾶς διεβίβασεν, ἐπινίκιον ᾄδοντας».

Καθαρθῶμεν τὰς αἰσθήσεις, καὶ ὀψόμεθα, τῷ ἀπροσίτῳ φωτὶ τῆς ἀναστάσεως, Χριστὸν ἐξαστράπτοντα, καί, Χαίρετε, φάσκοντα, τρανῶς ἀκουσόμεθα, ἐπινίκιον ᾄδοντες.

Οὐρανοὶ μὲν ἐπαξίως εὐφραινέσθωσαν, γῆ δὲ ἀγαλλιάσθω, ἑορταζέτω δὲ κόσμος, ὁρατός τε ἅπας καὶ ἀόρατος· Χριστὸς γὰρ ἐγήγερται, εὐφροσύνη αἰώνιος.
:::

Если постараться выделить индивидуальные элементы и свести их вручную, стараясь сохранить последовательность, то получится следующая структура:

+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Церковнославянский**                                                                                                                                                                                                                    | **Греческий**                                                                                                                                                     |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Канон Пасхальный,                                                                                                                                                                                                                         | Ὁ Κανών,                                                                                                                                                          |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| глас 1:                                                                                                                                                                                                                                   | \-                                                                                                                                                                |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| \-                                                                                                                                                                                                                                        | ποίημα Ἰωάννου τοῦ Δαμασκηνοῦ.                                                                                                                                    |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Пасхальный канон поется полностью хором: и ирмосы, и припевы, и тропари, и катавасии. На каждой песни канона совершается каждение. При соборном служении каждение совершают все иереи поочередно (а при большом числе иереев -- попарно). | \-                                                                                                                                                                |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Песнь 1:                                                                                                                                                                                                                                  | ᾨδὴ α'                                                                                                                                                            |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| \-                                                                                                                                                                                                                                        | Ἦχος α'                                                                                                                                                           |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Ирмос:                                                                                                                                                                                                                                    | εἱρμὸς                                                                                                                                                            |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Воскресе́ния день, просвети́мся, лю́дие. Па́сха, Госпо́дня Па́сха: от сме́рти бо к жи́зни, и от земли́ к небеси́, Христо́с Бог нас преведе́, побе́дную пою́щия.                                                                                         | «Ἀναστάσεως ἡμέρα λαμπρυνθῶμεν Λαοί, Πάσχα Κυρίου, Πάσχα· ἐκ γὰρ θανάτου πρὸς ζωήν, καὶ ἐκ γῆς πρὸς οὐρανόν, Χριστὸς ὁ Θεός, ἡμᾶς διεβίβασεν, ἐπινίκιον ᾄδοντας». |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Припев: Христо́с воскре́се из ме́ртвых.                                                                                                                                                                                                      | \-                                                                                                                                                                |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Очи́стим чу́вствия, и у́зрим непристу́пным све́том Воскресе́ния, Христа́ блиста́ющася, и ра́дуйтеся, реку́ща, я́сно да услы́шим, побе́дную пою́ще.                                                                                                      | Καθαρθῶμεν τὰς αἰσθήσεις, καὶ ὀψόμεθα, τῷ ἀπροσίτῳ φωτὶ τῆς ἀναστάσεως, Χριστὸν ἐξαστράπτοντα, καί, Χαίρετε, φάσκοντα, τρανῶς ἀκουσόμεθα, ἐπινίκιον ᾄδοντες.      |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| (6 раз)                                                                                                                                                                                                                                   | \-                                                                                                                                                                |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Небеса́ у́бо досто́йно да веселя́тся, земля́ же да ра́дуется, да пра́зднует же мир, ви́димый же весь и неви́димый: Христо́с бо воста́, весе́лие ве́чное.                                                                                               | Οὐρανοὶ μὲν ἐπαξίως εὐφραινέσθωσαν, γῆ δὲ ἀγαλλιάσθω, ἑορταζέτω δὲ κόσμος, ὁρατός τε ἅπας καὶ ἀόρατος· Χριστὸς γὰρ ἐγήγερται, εὐφροσύνη αἰώνιος.                  |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| (6 раз)                                                                                                                                                                                                                                   | \-                                                                                                                                                                |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+

На этом примере мы видим комбинацию всех рассмотренных [особенностей текста](010_pentekostarion.qmd#sec-about_pent_specifics):

-   **краткие и полные варианты**:

    -   служебные указания в церковнославянском тексте не имеют эквивалентов в греческом

-   **перекрестная структура**:

    -   элементы `Глас 1` и `Ἦχος α'`являются эквивалентами, но находятся в разных местах в текстах

-   **цветовая структура**:

    -   киноварные указания могут быть использованы как "якоря" для улучшения результатов элайнмента