# Готовые пакеты решений (элайнеры)

На начальных этапах проекта предполагалось использовать элайнеры – готовые программные решения для задачи выравнивания текстов: Lingtrain Aligner, а также Hunalign и его пользовательскую оболочку LF-aligner. Рассмотрим каждый из инструментов в отдельности.

## LF-aligner

*LF-aligner является графическим интерфейсом [Hunalign](https://github.com/danielvarga/hunalign)*. Этот инструмент требует предварительной лемматизации (ссылка на раздел) обрабатываемых текстов.

Алгоритм *Hunalign* решает задачу выравнивания лемматизированных текстов по предложениям или параграфам – что соответствует элементам молитв в нашем случае.

В *Hunalign* можно дополнительно подгрузить словарь переводных эквивалентов – в таком случае, алгоритм будет использовать его, комбинируя словарные данные с информацией о длине предложения по алгоритму Гейла-Черча.

В отсутствии внешнего словаря алгоритм сперва обращается к длине предложения, а затем автоматически генерирует словарь на основе результатов первичного выравнивания по длине. После этого *Hunalign* выравнивает текст повторно, используя сгенерированные словарные данные.

При работе с *Hunalign* возникает проблема, связанная с отсутствием параметров контроля окна сравнения единиц текста, из-за чего инструмент не может справиться со сложной перекрестной структурой Цветной Триоди (см. особенность 3 раздела Специфика текста Цветной триоди (в частности) и богослужебных текстов).

## Lingtrain-aligner

Среди преимуществ работы с [Lingtrain Aligner](https://github.com/averkij/lingtrain-aligner) стоит отметить нетребовательность инструмента к предварительной подготовке текстов, а также относительную простоту запуска алгоритмов выравнивания.

Пользователю не требуется осуществлять токенизацию и лемматизацию текста. Необходимо лишь определенным образом [разметить текст](https://habr.com/ru/articles/590549/) и убедиться, что он соответствует следующим параметрам:

- в случае если проставлены метки для заголовков, их число должно быть одинаковым для обоих текстов;
- в тексте отсутствуют строки, заканчивающиеся точкой и не являющиеся концом абзаца; в противном случае, абзацы будут сегментированы по точкам

Работать с подготовленными корпусами можно из python при помощи библиотеки lingtrain-aligner.

Предварительная разметка оказывается полезной не только для выравнивания в элайнерах, но также помогает при создании визуализации результатов – html-книги с параллельными текстами.

Формат выдачи результатов в виде html-книги, предусмотренный в lingtrain, не является оптимальным для целей проекта на данном этапе, поскольку мы заинтересованы в получении словаря переводных эквивалентов на уровне отдельных гимнов или предложений, а также в оценке качества выравнивания.

[Код](https://github.com/Drozhzhinastya/GSPC/blob/main/scripts/aligners/Lingtrain_LABse.ipynb) для работы с текстами Цветной Триоди.