# Направления дальнейшего исследования

Не смотря на то, что изначальные исследовательские цели проекта не финализированы на данном этапе, работа над проектом проявила множество особенностей обрабатываемых текстов. 

Мы прояснили [специфику текстов](010_pentekostarion.qmd#sec-about_pent_specifics) Цветной Триоди, важность [цветовой разметки](020_preprocessing.qmd#sec-html_color) для определения внутренней структуры текстов, оценили эффективность работы готовых [инструментов-элайнеров](030_aligners.qmd#sec-about_aligners), провели серию экспериментов по [лемматизации](040_lemmatization.qmd) билингвального корпуса, а также отметили наиболее проблемные аспекты и предложили [идеи](050_text_similarity.qmd) для поиска решений.

Проект продолжается. 

Мы – Настя и Лев – продолжаем исследовать изложенные в этом описании методы и инструменты, а также искать новые решения, которые могут приблизить проект к искомому результату.

:::{.callout-note icon=false appearance=simple title='Что дальше?'}
- использование мультиязычных моделей трансформеров с дообучением
- оптимизация алгоритма проверки качества сведения текстов
- выравнивание текстов Цветной Триоди с оценкой качества
- публикация параллельного корпуса на самостоятельной платформе или интеграция в [Liturcorpora](https://liturcorpora.ru/)
:::