project:
  type: book
  output-dir: docs

lang: ru

book:
  title: "Greek-Slavonic Parallel Corpus"
  author: "Лев Шадрин, Анастасия Дрожжина"
  date: today
  search: 
    location: sidebar
    type: textbox
  # downloads: [pdf, epub]
  chapters:
    - index.qmd
    
    - 010_pentekostarion.qmd

    - 020_preprocessing.qmd

    - 030_aligners.qmd

    - 040_lemmatization.qmd

    - 050_text_similarity.qmd

    - 060_evaluation.qmd

    - 070_perspectives.qmd
      
# bibliography: references.bib

format:
  html:
    theme: cosmo
    number-sections: false
  pdf:
    documentclass: book
    mainfont: "Mont"

# pdf-engine: lualatex

prefer-html: false

editor: visual

callout-appearance: simple
callout-icon: false

# execute:
#   execute_notebooks: force
#   allow_errors: true
#   cache: true 
