# О проекте {#sec-about_project}

Проект *Greek-Slavonic Parallel Corpus* (GSPC) является результатом работы студентов магистратуры "Цифровые методы в гуманитарных науках" НИУ ВШЭ.

Цель проекта -- создание алгоритма выравнивания богослужебных текстов сложной структуры внутри билингвального корпуса. На данном этапе работы для проектирования алгоритма используются тексты Цветной Триоди на греческом и церковнославянском языках.

Работа над проектом началась в декабре 2021 года в рамках научно-исследовательского проектного семинара программы "Цифровые методы в гуманитарных науках" НИУ-ВШЭ.

## Участники {#sec-authors}

-   Шадрин Лев `leo.shadrin@gmail.com`

-   Дрожжина Анастасия `drozhzhinastya@gmail.com`

## Незаменимые помощники проекта {#sec-acknowledgements}

-   *куратор проекта*: \
    игумен Пантелеимон (Королев), настоятель Данилова монастыря в Переславле-Залесском

-   *консультационная поддержка*: \
    Анастасия Александровна Бонч-Осмоловская, кан. филол. наук, доцент НИУ-ВШЭ

\